BaseField M, MM, X3, XX, Y3, gecc_optmp_1, t1, t2, t3, t4, t5, t6;
XX = x.square();
gecc_optmp_1 = (XX + XX).reduce_to_pp();
t1 = (gecc_optmp_1 + XX).reduce_to_pp();
BaseField a_mont = BaseField::load_const(ECDCONST.a_mont);
t2 = (t1 + a_mont).reduce_to_pp();
t3 = (y + y).reduce_to_pp();
M = t3.inverse();
M = t2 * M;
MM = M.square();
t4 = (x + x).reduce_to_pp();
X3 = (MM + BaseField::pp() - t4).reduce_to_pp();
t5 = (x + BaseField::pp() - X3).reduce_to_pp();
t6 = M * t5;
Y3 = (t6 + BaseField::pp() - y).reduce_to_pp();
Affine result;
result.x = X3.reduce_to_p();
result.y = Y3.reduce_to_p();
return result;
