BaseField M, MM, X3, XX, Y3, gecc_optmp_1, t1, t2, t3, t4, t5, t6;
XX = x.square();
gecc_optmp_1 = XX + XX;
t1 = gecc_optmp_1 + XX;
BaseField a_mont = BaseField::load_const(ECDCONST.a_mont);
t2 = (t1 + a_mont);
t3 = y + y;
M = t3.inverse();
M = t2 * M;
MM = M.square();
t4 = x + x;
X3 = MM - t4;
t5 = x - X3;
t6 = M * t5;
Y3 = t6 - y;
Affine result;
result.x = X3;
result.y = Y3;
return result;
