BaseField A, B, C, D, E, F, X3, Y3, Z3, gecc_optmp_1, gecc_optmp_2, gecc_optmp_3, t0, t1, t2, t3, t4, t5, t6, t7, t8;
A = x.square();
B = y.square();
C = B.square();
t0 = x + B;
t1 = t0.square();
t2 = t1 - A;
t3 = t2 - C;
D = t3 + t3;
gecc_optmp_1 = A + A;
E = gecc_optmp_1 + A;
F = E.square();
t4 = D + D;
X3 = F - t4;
t5 = D - X3;
gecc_optmp_2 = C + C;
gecc_optmp_3 = gecc_optmp_2 + gecc_optmp_2;
t6 = gecc_optmp_3 + gecc_optmp_3;
t7 = E * t5;
Y3 = t7 - t6;
t8 = y * z;
Z3 = t8 + t8;
ECPointJacobian result;
result.x = X3;
result.y = Y3;
result.z = Z3;
return result;
