BaseField M, S, T, X3, XX, Y3, YY, YYYY, Z3, gecc_optmp_1, gecc_optmp_2, gecc_optmp_3, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
XX = x.square();
YY = y.square();
YYYY = YY.square();
t0 = x + YY;
t1 = t0.square();
t2 = t1 - XX;
t3 = t2 - YYYY;
S = t3 + t3;
gecc_optmp_1 = XX + XX;
t4 = gecc_optmp_1 + XX;
BaseField a_mont = BaseField::load_const(ECDCONST.a_mont);
M = (t4 + a_mont);
t5 = M.square();
t6 = S + S;
T = t5 - t6;
X3 = T;
t7 = S - T;
gecc_optmp_2 = YYYY + YYYY;
gecc_optmp_3 = gecc_optmp_2 + gecc_optmp_2;
t8 = gecc_optmp_3 + gecc_optmp_3;
t9 = M * t7;
Y3 = t9 - t8;
Z3 = y + y;
ECPointJacobian result;
result.x = X3;
result.y = Y3;
result.z = Z3;
return result;
