BaseField M, S, T, X3, XX, Y3, YY, YYYY, Z3, gecc_optmp_1, gecc_optmp_2, gecc_optmp_3, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
XX = x.square();
YY = y.square();
YYYY = YY.square();
t0 = (x + YY).reduce_to_pp();
t1 = t0.square();
t2 = (t1 + BaseField::pp() - XX).reduce_to_pp();
t3 = (t2 + BaseField::pp() - YYYY).reduce_to_pp();
S = (t3 + t3).reduce_to_pp();
gecc_optmp_1 = (XX + XX).reduce_to_pp();
t4 = (gecc_optmp_1 + XX).reduce_to_pp();
BaseField a_mont = BaseField::load_const(ECDCONST.a_mont);
M = (t4 + a_mont).reduce_to_pp();
t5 = M.square();
t6 = (S + S).reduce_to_pp();
T = (t5 + BaseField::pp() - t6).reduce_to_pp();
X3 = T;
t7 = (S + BaseField::pp() - T).reduce_to_pp();
gecc_optmp_2 = (YYYY + YYYY).reduce_to_pp();
gecc_optmp_3 = (gecc_optmp_2 + gecc_optmp_2).reduce_to_pp();
t8 = (gecc_optmp_3 + gecc_optmp_3).reduce_to_pp();
t9 = M * t7;
Y3 = (t9 + BaseField::pp() - t8).reduce_to_pp();
Z3 = (y + y).reduce_to_pp();
ECPointJacobian result;
result.x = X3.reduce_to_p();
result.y = Y3.reduce_to_p();
result.z = Z3.reduce_to_p();
return result;
