BaseField M, S, T, X3, XX, Y3, YY, YYYY, Z3, ZZ, gecc_optmp_1, gecc_optmp_2, gecc_optmp_3, t0, t1, t10, t11, t12, t13, t14, t2, t3, t4, t5, t6, t7, t8, t9;
XX = x.square();
YY = y.square();
YYYY = YY.square();
ZZ = z.square();
t0 = (x + YY).reduce_to_pp();
t1 = t0.square();
t2 = (t1 + BaseField::pp() - XX).reduce_to_pp();
t3 = (t2 + BaseField::pp() - YYYY).reduce_to_pp();
S = (t3 + t3).reduce_to_pp();
t4 = ZZ.square();
t5 = MultiplicativeChain<BaseField, HCONST.a>::multiply(t4);
gecc_optmp_1 = (XX + XX).reduce_to_pp();
t6 = (gecc_optmp_1 + XX).reduce_to_pp();
M = (t6 + t5).reduce_to_pp();
t7 = M.square();
t8 = (S + S).reduce_to_pp();
T = (t7 + BaseField::pp() - t8).reduce_to_pp();
X3 = T;
t9 = (S + BaseField::pp() - T).reduce_to_pp();
gecc_optmp_2 = (YYYY + YYYY).reduce_to_pp();
gecc_optmp_3 = (gecc_optmp_2 + gecc_optmp_2).reduce_to_pp();
t10 = (gecc_optmp_3 + gecc_optmp_3).reduce_to_pp();
t11 = M * t9;
Y3 = (t11 + BaseField::pp() - t10).reduce_to_pp();
t12 = (y + z).reduce_to_pp();
t13 = t12.square();
t14 = (t13 + BaseField::pp() - YY).reduce_to_pp();
Z3 = (t14 + BaseField::pp() - ZZ).reduce_to_pp();
ECPointJacobian result;
result.x = X3.reduce_to_p();
result.y = Y3.reduce_to_p();
result.z = Z3.reduce_to_p();
return result;
