BaseField A, B, C, D, E, F, X3, Y3, Z3, gecc_optmp_1, gecc_optmp_2, gecc_optmp_3, t0, t1, t2, t3, t4, t5, t6, t7, t8;
A = x.square();
B = y.square();
C = B.square();
t0 = (x + B).reduce_to_pp();
t1 = t0.square();
t2 = (t1 + BaseField::pp() - A).reduce_to_pp();
t3 = (t2 + BaseField::pp() - C).reduce_to_pp();
D = (t3 + t3).reduce_to_pp();
gecc_optmp_1 = (A + A).reduce_to_pp();
E = (gecc_optmp_1 + A).reduce_to_pp();
F = E.square();
t4 = (D + D).reduce_to_pp();
X3 = (F + BaseField::pp() - t4).reduce_to_pp();
t5 = (D + BaseField::pp() - X3).reduce_to_pp();
gecc_optmp_2 = (C + C).reduce_to_pp();
gecc_optmp_3 = (gecc_optmp_2 + gecc_optmp_2).reduce_to_pp();
t6 = (gecc_optmp_3 + gecc_optmp_3).reduce_to_pp();
t7 = E * t5;
Y3 = (t7 + BaseField::pp() - t6).reduce_to_pp();
t8 = y * z;
Z3 = (t8 + t8).reduce_to_pp();
ECPointJacobian result;
result.x = X3.reduce_to_p();
result.y = Y3.reduce_to_p();
result.z = Z3.reduce_to_p();
return result;
